services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=10 # Poll every 10 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  expressapp:
    image: henryblue/express-app
    container_name: expressapp
    ports:
      - 8080:8080